services:
  # מסד הנתונים - MongoDB
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  # שרת ה-Backend (FastAPI)
  backend:
    build: ./server
    restart: always
    ports:
      - 8080:8080
    environment:
      - BASE_URL=http://98.83.47.167/
    depends_on:
      - mongo
    volumes:
      - ./server:/app
      - ./backend/static:/app/static

  # שרת ה-Frontend (React)
  frontend:
    build: ./client
    #volumes:
      #- ./client/dist:/usr/share/nginx/html
    restart: always
    ports:
      - 80:80
    depends_on:
      - backend

# זה החלק שהיה חסר או לא תקין:
volumes:
  mongo-data: